### ISSUE TITLE
Add support for I2S only builds that can still use HID control

### ISSUE THREAD

**Issue by andrewxcav** [xmos/lib_xua#368]
In principle this is very similar to running a standard USB audio design with I2S slave but:

- no audio needs to be sent over USB in either direction
- therefore no sample rate conversion or clock adaptation is needed
- there will also not be an external mclk (so any modules that expect one need to be bypassed or fail safe)

Tasks

- [x] Identify all places where mclk is consumed
- [x] Figure out which ones make sense to fix, i.e. if you are driving PDM mics you will still need an mclk
- [x] Add mclk free behavior while preserving the normal performance in all other cases

**Comment by andrewxcav** [comment]
First pass at occurrences (that are not simply mclk args being passed around through various wrappers):

lib_xua\lib_xua\src\core\
- main.xc
- audiohub\xua_audiohub.*
- buffer\decouple\decouple.xc (may be removed from list after fully understanding comment on line 516)
- buffer\ep\ep_buffer.xc ( """ line  651)
- endpoint0\xua_ep0_uacreqs.xc ( """ line 1136)
- ports\audioports.xc

**Comment by andrewxcav** [comment]
Unclear if these should be tied to XUA_USB_EN, of if these defines already imply it:

https://github.com/xmos/lib_xua/blob/05c8c446192bb48489515f1cfac84095ae0f04ee/lib_xua/src/core/main.xc#L274
https://github.com/xmos/lib_xua/blob/05c8c446192bb48489515f1cfac84095ae0f04ee/lib_xua/src/core/main.xc#L563

**Comment by andrewxcav** [comment]
What do these calls do when the clock arg is null (the caller is allowed to pass null to XUA_AudioHub, though this is never done in main, should we remove this freedom?)

https://github.com/xmos/lib_xua/blob/05c8c446192bb48489515f1cfac84095ae0f04ee/lib_xua/src/core/audiohub/xua_audiohub.xc#L671

**Comment by andrewxcav** [comment]
https://github.com/xmos/lib_xua/pull/372
I am sure there's a Github feature to link the issue to the PR, but it's eluding me.  Gitlab is so intuitive it ruined me for anything else.

**Comment by xross** [comment]
This should now be complete in that DFU/HID can be used with no UA interface. The mclk issue identified for I2S slave still exists.

**Comment by xross** [comment]
#439 should deal with the mclk issue
