### ISSUE TITLE
Default FLASH_MAX_UPGRADE_SIZE is small for modern devices

### ISSUE THREAD

**Issue by xross** [xmos/lib_xua#402]
#define FLASH_MAX_UPGRADE_SIZE (128 * 1024)

**Comment by xross** [comment]
Note, now we don't block the first write command having a large size is less of an issue.

**Comment by shuchitak** [comment]
As part of https://github.com/xmos/lib_xua/pull/424, I've changed the default FLASH_MAX_UPGRADE_SIZE to (512 * 1024)
